<?php

require_once dirname(__FILE__) . '/../Count.php';

/**
 * Test class for Count.
 * Generated by PHPUnit on 2012-01-11 at 16:18:39.
 */
class CountTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Count
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Count();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testCountEmpty() {
        $this->assertEquals(0, $this->object->countLines(array()));
    }
    
    public function testCountOneLine() {
        $this->assertEquals(1, $this->object->countLines(array('foo')));
    }
    
    public function testCountOneLineOneComment() {
        $this->assertEquals(1, $this->object->countLines(array('foo','// comment')));
    }
    
    public function testCountOneLineOneCommentWithSpaces() {
        $this->assertEquals(1, $this->object->countLines(array('foo','   // comment')));
    }
    
    public function testCountTwoLinesNoComment() {
        $this->assertEquals(2, $this->object->countLines(array('foo','echo $foo   // comment')));
    }
    
    public function testCountLinesLongComment() {
        $this->assertEquals(2, $this->object->countLines(array(
            'foo',
            '/*foo*/',
            'echo $foo   // comment'
            )));
    }
    
    public function testCountLinesLongCommentAfter() {
        $this->assertEquals(3, $this->object->countLines(array(
            'foo',
            '/*foo*/ echo',
            'echo $foo   // comment'
            )));
    }
    
    public function testTwoBlockCommentsInOneLine() {
        $this->assertEquals(2, $this->object->countLines(array(
            'foo',
            '/*foo*/  /*foo*/',
            'echo $foo   // comment'
            )));
    }
    
    public function testTwoBlockCommentsInOneLineWithCode() {
        $this->assertEquals(3, $this->object->countLines(array(
            'foo',
            '/*foo*/ echo /*foo*/',
            'echo $foo   // comment'
            )));
    }
    
    public function testTwoBlockCommentsInTwoLines() {
        $this->assertEquals(2, $this->object->countLines(array(
            'foo',
            '/*foo',
            'foo*/',
            'echo $foo   // comment'
            )));
    }
    
    public function testTwoBlockCommentsInTwoLinesWithCode() {
        $this->assertEquals(3, $this->object->countLines(array(
            'foo',
            'echo /*foo',
            'foo*/',
            'echo $foo   // comment'
            )));
    }
   
    public function testTwoBlockCommentsInThreeLinesWithCode() {
        $this->assertEquals(3, $this->object->countLines(array(
            'eins',
            'zwei /*foo',
            'drei',
            'vier*/',
            'fuenf   // comment'
            )));
    }
    
    
}

?>
